name: 'Testing the entire website'
on: pull_request
jobs:
  eslint-jest-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repo'
        uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: 'Install repo'
        run: npm install
      - name: 'Build the site'
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      - name: 'Start the server and run tests'
        run: npm run ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_CUSTOMER_PORTAL_URL: ${{ secrets.NEXT_PUBLIC_CUSTOMER_PORTAL_URL }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_MANAGEMENT_API_CLIENT_ID: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_ID }}
          AUTH0_MANAGEMENT_API_CLIENT_SECRET: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_SECRET }}
          CYPRESS_AUTH0AUDIENCE: ${{ secrets.CYPRESS_AUTH0AUDIENCE }}
          CYPRESS_AUTH0CLIENTID: ${{ secrets.CYPRESS_AUTH0CLIENTID }}
          CYPRESS_AUTH0CLIENTSECRET: ${{ secrets.CYPRESS_AUTH0CLIENTSECRET }}
          CYPRESS_AUTH0COOKIESECRET: ${{ secrets.CYPRESS_AUTH0COOKIESECRET }}
          CYPRESS_AUTH0DOMAIN: ${{ secrets.CYPRESS_AUTH0DOMAIN }}
          CYPRESS_AUTH0LOGOUTURL: ${{ secrets.CYPRESS_AUTH0LOGOUTURL }}
          CYPRESS_AUTH0PASSCANCELLED: ${{ secrets.CYPRESS_AUTH0PASSCANCELLED }}
          CYPRESS_AUTH0PASSSUBSCRIBED1: ${{ secrets.CYPRESS_AUTH0PASSSUBSCRIBED1 }}
          CYPRESS_AUTH0PASSSUBSCRIBED2: ${{ secrets.CYPRESS_AUTH0PASSSUBSCRIBED2 }}
          CYPRESS_AUTH0PASSSUBSCRIPTIONEXPIRED: ${{ secrets.CYPRESS_AUTH0PASSSUBSCRIPTIONEXPIRED }}
          CYPRESS_AUTH0PASSTRIAL: ${{ secrets.CYPRESS_AUTH0PASSTRIAL }}
          CYPRESS_AUTH0PASSTRIALEXPIRED: ${{ secrets.CYPRESS_AUTH0PASSTRIALEXPIRED }}
          CYPRESS_AUTH0PASSUNPAID: ${{ secrets.CYPRESS_AUTH0PASSUNPAID }}
          CYPRESS_AUTH0RETURNTOURL: ${{ secrets.CYPRESS_AUTH0RETURNTOURL }}
          CYPRESS_AUTH0SCOPE: ${{ secrets.CYPRESS_AUTH0SCOPE }}
          CYPRESS_AUTH0SESSIONCOOKIENAME: ${{ secrets.CYPRESS_AUTH0SESSIONCOOKIENAME }}
          CYPRESS_AUTH0USERCANCELLED: ${{ secrets.CYPRESS_AUTH0USERCANCELLED }}
          CYPRESS_AUTH0USERSUBSCRIBED1: ${{ secrets.CYPRESS_AUTH0USERSUBSCRIBED1 }}
          CYPRESS_AUTH0USERSUBSCRIBED2: ${{ secrets.CYPRESS_AUTH0USERSUBSCRIBED2 }}
          CYPRESS_AUTH0USERSUBSCRIPTIONEXPIRED: ${{ secrets.CYPRESS_AUTH0USERSUBSCRIPTIONEXPIRED }}
          CYPRESS_AUTH0USERTRIAL: ${{ secrets.CYPRESS_AUTH0USERTRIAL }}
          CYPRESS_AUTH0USERTRIALEXPIRED: ${{ secrets.CYPRESS_AUTH0USERTRIALEXPIRED }}
          CYPRESS_AUTH0USERUNPAID: ${{ secrets.CYPRESS_AUTH0USERUNPAID }}
          CYPRESS_CUSTOMER_PORTAL_URL: ${{ secrets.CYPRESS_CUSTOMER_PORTAL_URL }}
